### PR TITLE
First Pull Request :-)

### PR DESCRIPTION
**Pull request by 4Reallive**
Pull Request to test it out and let you know this is alive.
Realized i should be focusing on Terrform first and ansible roles later. ( Also learning git at same time)
Hardest part is starting i will contribute more regularly from now on. Thanks for your patience TRTLs
(It's a work in progress it will be nice and neat later)

To Do from here (more tasks in README file)
- Make the code more flexible and reusable (better use of variables, functions/files etc.) Tidy up/Doc
- Deploy multiple nodes
- Deploy Docker images
- Deploy Load Balancer to work with various node configurations
- Wrap in a shell script
- AWS Integration

### CODE REVIEW

**Comment by SoreGums** [comment]
nice - is  this file supposed to be in here?
`https://github.com/turtlecoin/krang/pull/3/files#diff-edd5b7b4c4cac36a95382c4269c4eefa`

**Comment by 4Reallive** [comment]
no its not meant to be in there,
Ill get back onto this stuff soon.
Good pickup

**Comment by SoreGums** [comment]
Think you need to gitignore the .terraform directory. That lock.json file doesn't look like it ought to be i n the repo ;)

**Comment by 4Reallive** [comment]
it is .gitignored
i must have added it somehow, fixing it now.

**Comment by SoreGums** [comment]
Cool. Looks great

I think maybe you need to checkout the repo again and do a copy paste and then push.

Else I'm going to have to squash your commit and then re-add the readme back ;)

**Pull request closed without merging**
